//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GamesClass", Namespace="http://schemas.datacontract.org/2004/07/omerWCF.App_Code")]
    [System.SerializableAttribute()]
    public partial class GamesClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameNUmverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Game_levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayersPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PointsInTheGameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShootNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Victory1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameNUmver {
            get {
                return this.GameNUmverField;
            }
            set {
                if ((this.GameNUmverField.Equals(value) != true)) {
                    this.GameNUmverField = value;
                    this.RaisePropertyChanged("GameNUmver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Game_level {
            get {
                return this.Game_levelField;
            }
            set {
                if ((this.Game_levelField.Equals(value) != true)) {
                    this.Game_levelField = value;
                    this.RaisePropertyChanged("Game_level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayersPlayed {
            get {
                return this.PlayersPlayedField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersPlayedField, value) != true)) {
                    this.PlayersPlayedField = value;
                    this.RaisePropertyChanged("PlayersPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PointsInTheGame {
            get {
                return this.PointsInTheGameField;
            }
            set {
                if ((object.ReferenceEquals(this.PointsInTheGameField, value) != true)) {
                    this.PointsInTheGameField = value;
                    this.RaisePropertyChanged("PointsInTheGame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShootNumber {
            get {
                return this.ShootNumberField;
            }
            set {
                if ((this.ShootNumberField.Equals(value) != true)) {
                    this.ShootNumberField = value;
                    this.RaisePropertyChanged("ShootNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Victory1 {
            get {
                return this.Victory1Field;
            }
            set {
                if ((this.Victory1Field.Equals(value) != true)) {
                    this.Victory1Field = value;
                    this.RaisePropertyChanged("Victory1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayrsClass", Namespace="http://schemas.datacontract.org/2004/07/omerWCF.App_Code")]
    [System.SerializableAttribute()]
    public partial class PlayrsClass : WebApplication1.ServiceReference1.HumanSource {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AST1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BLK1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GP1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Level1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayedINLeagues1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int STL1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TO1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkoutDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fGMField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AST1 {
            get {
                return this.AST1Field;
            }
            set {
                if ((this.AST1Field.Equals(value) != true)) {
                    this.AST1Field = value;
                    this.RaisePropertyChanged("AST1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BLK1 {
            get {
                return this.BLK1Field;
            }
            set {
                if ((this.BLK1Field.Equals(value) != true)) {
                    this.BLK1Field = value;
                    this.RaisePropertyChanged("BLK1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GP1 {
            get {
                return this.GP1Field;
            }
            set {
                if ((this.GP1Field.Equals(value) != true)) {
                    this.GP1Field = value;
                    this.RaisePropertyChanged("GP1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName1 {
            get {
                return this.LastName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LastName1Field, value) != true)) {
                    this.LastName1Field = value;
                    this.RaisePropertyChanged("LastName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level1 {
            get {
                return this.Level1Field;
            }
            set {
                if ((this.Level1Field.Equals(value) != true)) {
                    this.Level1Field = value;
                    this.RaisePropertyChanged("Level1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayedINLeagues1 {
            get {
                return this.PlayedINLeagues1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PlayedINLeagues1Field, value) != true)) {
                    this.PlayedINLeagues1Field = value;
                    this.RaisePropertyChanged("PlayedINLeagues1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerNumber {
            get {
                return this.PlayerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNumberField, value) != true)) {
                    this.PlayerNumberField = value;
                    this.RaisePropertyChanged("PlayerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int STL1 {
            get {
                return this.STL1Field;
            }
            set {
                if ((this.STL1Field.Equals(value) != true)) {
                    this.STL1Field = value;
                    this.RaisePropertyChanged("STL1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TO1 {
            get {
                return this.TO1Field;
            }
            set {
                if ((this.TO1Field.Equals(value) != true)) {
                    this.TO1Field = value;
                    this.RaisePropertyChanged("TO1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainerID {
            get {
                return this.TrainerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainerIDField, value) != true)) {
                    this.TrainerIDField = value;
                    this.RaisePropertyChanged("TrainerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkoutDays {
            get {
                return this.WorkoutDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkoutDaysField, value) != true)) {
                    this.WorkoutDaysField = value;
                    this.RaisePropertyChanged("WorkoutDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fGM {
            get {
                return this.fGMField;
            }
            set {
                if ((this.fGMField.Equals(value) != true)) {
                    this.fGMField = value;
                    this.RaisePropertyChanged("fGM");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanSource", Namespace="http://schemas.datacontract.org/2004/07/omerWCF.App_Code")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.TrainersClass))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebApplication1.ServiceReference1.PlayrsClass))]
    public partial class HumanSource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainersClass", Namespace="http://schemas.datacontract.org/2004/07/omerWCF.App_Code")]
    [System.SerializableAttribute()]
    public partial class TrainersClass : WebApplication1.ServiceReference1.HumanSource {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fname1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Level1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Lname1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartWorkingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname1 {
            get {
                return this.Fname1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Fname1Field, value) != true)) {
                    this.Fname1Field = value;
                    this.RaisePropertyChanged("Fname1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level1 {
            get {
                return this.Level1Field;
            }
            set {
                if ((this.Level1Field.Equals(value) != true)) {
                    this.Level1Field = value;
                    this.RaisePropertyChanged("Level1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname1 {
            get {
                return this.Lname1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Lname1Field, value) != true)) {
                    this.Lname1Field = value;
                    this.RaisePropertyChanged("Lname1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartWorking {
            get {
                return this.StartWorkingField;
            }
            set {
                if ((this.StartWorkingField.Equals(value) != true)) {
                    this.StartWorkingField = value;
                    this.RaisePropertyChanged("StartWorking");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainingClass", Namespace="http://schemas.datacontract.org/2004/07/omerWCF.App_Code")]
    [System.SerializableAttribute()]
    public partial class TrainingClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainingHouer1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TrainingLevel1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkoutDayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainerID {
            get {
                return this.TrainerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainerIDField, value) != true)) {
                    this.TrainerIDField = value;
                    this.RaisePropertyChanged("TrainerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainingHouer1 {
            get {
                return this.TrainingHouer1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingHouer1Field, value) != true)) {
                    this.TrainingHouer1Field = value;
                    this.RaisePropertyChanged("TrainingHouer1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TrainingLevel1 {
            get {
                return this.TrainingLevel1Field;
            }
            set {
                if ((this.TrainingLevel1Field.Equals(value) != true)) {
                    this.TrainingLevel1Field = value;
                    this.RaisePropertyChanged("TrainingLevel1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainingType {
            get {
                return this.TrainingTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingTypeField, value) != true)) {
                    this.TrainingTypeField = value;
                    this.RaisePropertyChanged("TrainingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkoutDay {
            get {
                return this.WorkoutDayField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkoutDayField, value) != true)) {
                    this.WorkoutDayField = value;
                    this.RaisePropertyChanged("WorkoutDay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LeaguesClass", Namespace="http://schemas.datacontract.org/2004/07/omerWCF.App_Code")]
    [System.SerializableAttribute()]
    public partial class LeaguesClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BastPlayerAtTheLeague1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoachName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeagueLevel1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeagueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PTSatLeague1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BastPlayerAtTheLeague1 {
            get {
                return this.BastPlayerAtTheLeague1Field;
            }
            set {
                if ((object.ReferenceEquals(this.BastPlayerAtTheLeague1Field, value) != true)) {
                    this.BastPlayerAtTheLeague1Field = value;
                    this.RaisePropertyChanged("BastPlayerAtTheLeague1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoachName1 {
            get {
                return this.CoachName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CoachName1Field, value) != true)) {
                    this.CoachName1Field = value;
                    this.RaisePropertyChanged("CoachName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeagueLevel1 {
            get {
                return this.LeagueLevel1Field;
            }
            set {
                if ((this.LeagueLevel1Field.Equals(value) != true)) {
                    this.LeagueLevel1Field = value;
                    this.RaisePropertyChanged("LeagueLevel1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeagueName {
            get {
                return this.LeagueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LeagueNameField, value) != true)) {
                    this.LeagueNameField = value;
                    this.RaisePropertyChanged("LeagueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PTSatLeague1 {
            get {
                return this.PTSatLeague1Field;
            }
            set {
                if ((this.PTSatLeague1Field.Equals(value) != true)) {
                    this.PTSatLeague1Field = value;
                    this.RaisePropertyChanged("PTSatLeague1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginClass", Namespace="http://schemas.datacontract.org/2004/07/omerWCF.App_Code")]
    [System.SerializableAttribute()]
    public partial class LoginClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGame", ReplyAction="http://tempuri.org/IService1/AddGameResponse")]
        int AddGame(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddGame", ReplyAction="http://tempuri.org/IService1/AddGameResponse")]
        System.Threading.Tasks.Task<int> AddGameAsync(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintGamesList", ReplyAction="http://tempuri.org/IService1/PrintGamesListResponse")]
        WebApplication1.ServiceReference1.GamesClass[] PrintGamesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintGamesList", ReplyAction="http://tempuri.org/IService1/PrintGamesListResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GamesClass[]> PrintGamesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintPlayersList", ReplyAction="http://tempuri.org/IService1/PrintPlayersListResponse")]
        WebApplication1.ServiceReference1.PlayrsClass[] PrintPlayersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintPlayersList", ReplyAction="http://tempuri.org/IService1/PrintPlayersListResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.PlayrsClass[]> PrintPlayersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTrainer", ReplyAction="http://tempuri.org/IService1/AddTrainerResponse")]
        int AddTrainer(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTrainer", ReplyAction="http://tempuri.org/IService1/AddTrainerResponse")]
        System.Threading.Tasks.Task<int> AddTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTrainer", ReplyAction="http://tempuri.org/IService1/DeleteTrainerResponse")]
        int DeleteTrainer(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTrainer", ReplyAction="http://tempuri.org/IService1/DeleteTrainerResponse")]
        System.Threading.Tasks.Task<int> DeleteTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectTrainer", ReplyAction="http://tempuri.org/IService1/SelectTrainerResponse")]
        WebApplication1.ServiceReference1.TrainersClass SelectTrainer(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectTrainer", ReplyAction="http://tempuri.org/IService1/SelectTrainerResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainersClass> SelectTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTrainer", ReplyAction="http://tempuri.org/IService1/UpdateTrainerResponse")]
        int UpdateTrainer(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTrainer", ReplyAction="http://tempuri.org/IService1/UpdateTrainerResponse")]
        System.Threading.Tasks.Task<int> UpdateTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintTrainersLinst", ReplyAction="http://tempuri.org/IService1/PrintTrainersLinstResponse")]
        WebApplication1.ServiceReference1.TrainersClass[] PrintTrainersLinst();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintTrainersLinst", ReplyAction="http://tempuri.org/IService1/PrintTrainersLinstResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainersClass[]> PrintTrainersLinstAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTraining", ReplyAction="http://tempuri.org/IService1/AddTrainingResponse")]
        int AddTraining(WebApplication1.ServiceReference1.TrainingClass train);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddTraining", ReplyAction="http://tempuri.org/IService1/AddTrainingResponse")]
        System.Threading.Tasks.Task<int> AddTrainingAsync(WebApplication1.ServiceReference1.TrainingClass train);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTraining", ReplyAction="http://tempuri.org/IService1/DeleteTrainingResponse")]
        int DeleteTraining(WebApplication1.ServiceReference1.TrainingClass train);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteTraining", ReplyAction="http://tempuri.org/IService1/DeleteTrainingResponse")]
        System.Threading.Tasks.Task<int> DeleteTrainingAsync(WebApplication1.ServiceReference1.TrainingClass train);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectTraining", ReplyAction="http://tempuri.org/IService1/SelectTrainingResponse")]
        WebApplication1.ServiceReference1.TrainingClass SelectTraining(WebApplication1.ServiceReference1.TrainingClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectTraining", ReplyAction="http://tempuri.org/IService1/SelectTrainingResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainingClass> SelectTrainingAsync(WebApplication1.ServiceReference1.TrainingClass trainer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintTraningList", ReplyAction="http://tempuri.org/IService1/PrintTraningListResponse")]
        WebApplication1.ServiceReference1.TrainingClass[] PrintTraningList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintTraningList", ReplyAction="http://tempuri.org/IService1/PrintTraningListResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainingClass[]> PrintTraningListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLeague", ReplyAction="http://tempuri.org/IService1/AddLeagueResponse")]
        int AddLeague(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLeague", ReplyAction="http://tempuri.org/IService1/AddLeagueResponse")]
        System.Threading.Tasks.Task<int> AddLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLeague", ReplyAction="http://tempuri.org/IService1/DeleteLeagueResponse")]
        int DeleteLeague(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLeague", ReplyAction="http://tempuri.org/IService1/DeleteLeagueResponse")]
        System.Threading.Tasks.Task<int> DeleteLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectLeague", ReplyAction="http://tempuri.org/IService1/SelectLeagueResponse")]
        WebApplication1.ServiceReference1.LeaguesClass SelectLeague(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectLeague", ReplyAction="http://tempuri.org/IService1/SelectLeagueResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.LeaguesClass> SelectLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintLeaguesList", ReplyAction="http://tempuri.org/IService1/PrintLeaguesListResponse")]
        WebApplication1.ServiceReference1.LeaguesClass[] PrintLeaguesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintLeaguesList", ReplyAction="http://tempuri.org/IService1/PrintLeaguesListResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.LeaguesClass[]> PrintLeaguesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLeague", ReplyAction="http://tempuri.org/IService1/UpdateLeagueResponse")]
        int UpdateLeague(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLeague", ReplyAction="http://tempuri.org/IService1/UpdateLeagueResponse")]
        System.Threading.Tasks.Task<int> UpdateLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPlayer", ReplyAction="http://tempuri.org/IService1/AddPlayerResponse")]
        int AddPlayer(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPlayer", ReplyAction="http://tempuri.org/IService1/AddPlayerResponse")]
        System.Threading.Tasks.Task<int> AddPlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlayer", ReplyAction="http://tempuri.org/IService1/DeletePlayerResponse")]
        int DeletePlayer(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlayer", ReplyAction="http://tempuri.org/IService1/DeletePlayerResponse")]
        System.Threading.Tasks.Task<int> DeletePlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePlayer", ReplyAction="http://tempuri.org/IService1/UpdatePlayerResponse")]
        int UpdatePlayer(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdatePlayer", ReplyAction="http://tempuri.org/IService1/UpdatePlayerResponse")]
        System.Threading.Tasks.Task<int> UpdatePlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPlayer", ReplyAction="http://tempuri.org/IService1/SelectPlayerResponse")]
        WebApplication1.ServiceReference1.PlayrsClass SelectPlayer(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectPlayer", ReplyAction="http://tempuri.org/IService1/SelectPlayerResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.PlayrsClass> SelectPlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGame", ReplyAction="http://tempuri.org/IService1/DeleteGameResponse")]
        int DeleteGame(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteGame", ReplyAction="http://tempuri.org/IService1/DeleteGameResponse")]
        System.Threading.Tasks.Task<int> DeleteGameAsync(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGame", ReplyAction="http://tempuri.org/IService1/UpdateGameResponse")]
        int UpdateGame(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateGame", ReplyAction="http://tempuri.org/IService1/UpdateGameResponse")]
        System.Threading.Tasks.Task<int> UpdateGameAsync(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGame", ReplyAction="http://tempuri.org/IService1/SelectGameResponse")]
        WebApplication1.ServiceReference1.GamesClass SelectGame(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectGame", ReplyAction="http://tempuri.org/IService1/SelectGameResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GamesClass> SelectGameAsync(WebApplication1.ServiceReference1.GamesClass game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTraining", ReplyAction="http://tempuri.org/IService1/UpdateTrainingResponse")]
        int UpdateTraining(WebApplication1.ServiceReference1.TrainingClass train);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateTraining", ReplyAction="http://tempuri.org/IService1/UpdateTrainingResponse")]
        System.Threading.Tasks.Task<int> UpdateTrainingAsync(WebApplication1.ServiceReference1.TrainingClass train);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signUp", ReplyAction="http://tempuri.org/IService1/signUpResponse")]
        int signUp(WebApplication1.ServiceReference1.LoginClass user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signUp", ReplyAction="http://tempuri.org/IService1/signUpResponse")]
        System.Threading.Tasks.Task<int> signUpAsync(WebApplication1.ServiceReference1.LoginClass user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        string login(WebApplication1.ServiceReference1.LoginClass user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/login", ReplyAction="http://tempuri.org/IService1/loginResponse")]
        System.Threading.Tasks.Task<string> loginAsync(WebApplication1.ServiceReference1.LoginClass user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTrainersSalaryBySeniority", ReplyAction="http://tempuri.org/IService1/GetTrainersSalaryBySeniorityResponse")]
        WebApplication1.ServiceReference1.TrainersClass[] GetTrainersSalaryBySeniority();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTrainersSalaryBySeniority", ReplyAction="http://tempuri.org/IService1/GetTrainersSalaryBySeniorityResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainersClass[]> GetTrainersSalaryBySeniorityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLeaguesChartData", ReplyAction="http://tempuri.org/IService1/GetLeaguesChartDataResponse")]
        WebApplication1.ServiceReference1.LeaguesClass[] GetLeaguesChartData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLeaguesChartData", ReplyAction="http://tempuri.org/IService1/GetLeaguesChartDataResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.LeaguesClass[]> GetLeaguesChartDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWeakPlayers", ReplyAction="http://tempuri.org/IService1/GetWeakPlayersResponse")]
        WebApplication1.ServiceReference1.PlayrsClass[] GetWeakPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWeakPlayers", ReplyAction="http://tempuri.org/IService1/GetWeakPlayersResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.PlayrsClass[]> GetWeakPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWinCount", ReplyAction="http://tempuri.org/IService1/GetWinCountResponse")]
        int GetWinCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWinCount", ReplyAction="http://tempuri.org/IService1/GetWinCountResponse")]
        System.Threading.Tasks.Task<int> GetWinCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLossCount", ReplyAction="http://tempuri.org/IService1/GetLossCountResponse")]
        int GetLossCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLossCount", ReplyAction="http://tempuri.org/IService1/GetLossCountResponse")]
        System.Threading.Tasks.Task<int> GetLossCountAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IService1>, WebApplication1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddGame(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.AddGame(game);
        }
        
        public System.Threading.Tasks.Task<int> AddGameAsync(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.AddGameAsync(game);
        }
        
        public WebApplication1.ServiceReference1.GamesClass[] PrintGamesList() {
            return base.Channel.PrintGamesList();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GamesClass[]> PrintGamesListAsync() {
            return base.Channel.PrintGamesListAsync();
        }
        
        public WebApplication1.ServiceReference1.PlayrsClass[] PrintPlayersList() {
            return base.Channel.PrintPlayersList();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.PlayrsClass[]> PrintPlayersListAsync() {
            return base.Channel.PrintPlayersListAsync();
        }
        
        public int AddTrainer(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.AddTrainer(trainer);
        }
        
        public System.Threading.Tasks.Task<int> AddTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.AddTrainerAsync(trainer);
        }
        
        public int DeleteTrainer(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.DeleteTrainer(trainer);
        }
        
        public System.Threading.Tasks.Task<int> DeleteTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.DeleteTrainerAsync(trainer);
        }
        
        public WebApplication1.ServiceReference1.TrainersClass SelectTrainer(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.SelectTrainer(trainer);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainersClass> SelectTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.SelectTrainerAsync(trainer);
        }
        
        public int UpdateTrainer(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.UpdateTrainer(trainer);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTrainerAsync(WebApplication1.ServiceReference1.TrainersClass trainer) {
            return base.Channel.UpdateTrainerAsync(trainer);
        }
        
        public WebApplication1.ServiceReference1.TrainersClass[] PrintTrainersLinst() {
            return base.Channel.PrintTrainersLinst();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainersClass[]> PrintTrainersLinstAsync() {
            return base.Channel.PrintTrainersLinstAsync();
        }
        
        public int AddTraining(WebApplication1.ServiceReference1.TrainingClass train) {
            return base.Channel.AddTraining(train);
        }
        
        public System.Threading.Tasks.Task<int> AddTrainingAsync(WebApplication1.ServiceReference1.TrainingClass train) {
            return base.Channel.AddTrainingAsync(train);
        }
        
        public int DeleteTraining(WebApplication1.ServiceReference1.TrainingClass train) {
            return base.Channel.DeleteTraining(train);
        }
        
        public System.Threading.Tasks.Task<int> DeleteTrainingAsync(WebApplication1.ServiceReference1.TrainingClass train) {
            return base.Channel.DeleteTrainingAsync(train);
        }
        
        public WebApplication1.ServiceReference1.TrainingClass SelectTraining(WebApplication1.ServiceReference1.TrainingClass trainer) {
            return base.Channel.SelectTraining(trainer);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainingClass> SelectTrainingAsync(WebApplication1.ServiceReference1.TrainingClass trainer) {
            return base.Channel.SelectTrainingAsync(trainer);
        }
        
        public WebApplication1.ServiceReference1.TrainingClass[] PrintTraningList() {
            return base.Channel.PrintTraningList();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainingClass[]> PrintTraningListAsync() {
            return base.Channel.PrintTraningListAsync();
        }
        
        public int AddLeague(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.AddLeague(league);
        }
        
        public System.Threading.Tasks.Task<int> AddLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.AddLeagueAsync(league);
        }
        
        public int DeleteLeague(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.DeleteLeague(league);
        }
        
        public System.Threading.Tasks.Task<int> DeleteLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.DeleteLeagueAsync(league);
        }
        
        public WebApplication1.ServiceReference1.LeaguesClass SelectLeague(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.SelectLeague(league);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.LeaguesClass> SelectLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.SelectLeagueAsync(league);
        }
        
        public WebApplication1.ServiceReference1.LeaguesClass[] PrintLeaguesList() {
            return base.Channel.PrintLeaguesList();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.LeaguesClass[]> PrintLeaguesListAsync() {
            return base.Channel.PrintLeaguesListAsync();
        }
        
        public int UpdateLeague(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.UpdateLeague(league);
        }
        
        public System.Threading.Tasks.Task<int> UpdateLeagueAsync(WebApplication1.ServiceReference1.LeaguesClass league) {
            return base.Channel.UpdateLeagueAsync(league);
        }
        
        public int AddPlayer(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.AddPlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> AddPlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.AddPlayerAsync(player);
        }
        
        public int DeletePlayer(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.DeletePlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> DeletePlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.DeletePlayerAsync(player);
        }
        
        public int UpdatePlayer(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.UpdatePlayer(player);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.UpdatePlayerAsync(player);
        }
        
        public WebApplication1.ServiceReference1.PlayrsClass SelectPlayer(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.SelectPlayer(player);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.PlayrsClass> SelectPlayerAsync(WebApplication1.ServiceReference1.PlayrsClass player) {
            return base.Channel.SelectPlayerAsync(player);
        }
        
        public int DeleteGame(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.DeleteGame(game);
        }
        
        public System.Threading.Tasks.Task<int> DeleteGameAsync(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.DeleteGameAsync(game);
        }
        
        public int UpdateGame(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.UpdateGame(game);
        }
        
        public System.Threading.Tasks.Task<int> UpdateGameAsync(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.UpdateGameAsync(game);
        }
        
        public WebApplication1.ServiceReference1.GamesClass SelectGame(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.SelectGame(game);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.GamesClass> SelectGameAsync(WebApplication1.ServiceReference1.GamesClass game) {
            return base.Channel.SelectGameAsync(game);
        }
        
        public int UpdateTraining(WebApplication1.ServiceReference1.TrainingClass train) {
            return base.Channel.UpdateTraining(train);
        }
        
        public System.Threading.Tasks.Task<int> UpdateTrainingAsync(WebApplication1.ServiceReference1.TrainingClass train) {
            return base.Channel.UpdateTrainingAsync(train);
        }
        
        public int signUp(WebApplication1.ServiceReference1.LoginClass user) {
            return base.Channel.signUp(user);
        }
        
        public System.Threading.Tasks.Task<int> signUpAsync(WebApplication1.ServiceReference1.LoginClass user) {
            return base.Channel.signUpAsync(user);
        }
        
        public string login(WebApplication1.ServiceReference1.LoginClass user) {
            return base.Channel.login(user);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(WebApplication1.ServiceReference1.LoginClass user) {
            return base.Channel.loginAsync(user);
        }
        
        public WebApplication1.ServiceReference1.TrainersClass[] GetTrainersSalaryBySeniority() {
            return base.Channel.GetTrainersSalaryBySeniority();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.TrainersClass[]> GetTrainersSalaryBySeniorityAsync() {
            return base.Channel.GetTrainersSalaryBySeniorityAsync();
        }
        
        public WebApplication1.ServiceReference1.LeaguesClass[] GetLeaguesChartData() {
            return base.Channel.GetLeaguesChartData();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.LeaguesClass[]> GetLeaguesChartDataAsync() {
            return base.Channel.GetLeaguesChartDataAsync();
        }
        
        public WebApplication1.ServiceReference1.PlayrsClass[] GetWeakPlayers() {
            return base.Channel.GetWeakPlayers();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.PlayrsClass[]> GetWeakPlayersAsync() {
            return base.Channel.GetWeakPlayersAsync();
        }
        
        public int GetWinCount() {
            return base.Channel.GetWinCount();
        }
        
        public System.Threading.Tasks.Task<int> GetWinCountAsync() {
            return base.Channel.GetWinCountAsync();
        }
        
        public int GetLossCount() {
            return base.Channel.GetLossCount();
        }
        
        public System.Threading.Tasks.Task<int> GetLossCountAsync() {
            return base.Channel.GetLossCountAsync();
        }
    }
}
